### ISSUE TITLE
Implement firecracker-control GRPC plugin

### ISSUE THREAD

**Issue by mxpv** [firecracker-microvm/firecracker-containerd#159]
Implement a GRPC plugin for containerd to manage Firecracker VM instance(s) 

- [x] Basic implementation: https://github.com/firecracker-microvm/firecracker-containerd/pull/156
- [x] Generate containerd events (vm start, vm exit)
- [x] Remove TODOs after merging PRs: firecracker-microvm/firecracker-go-sdk#91, firecracker-microvm/firecracker-go-sdk#90
- [x] Handle containerd shutdown properly? (shutdown FC instances)
- [x] Add collision detection for generated IDs.
- [x] Figure out how to reuse containerd Client conn object with grpc plugins - https://github.com/containerd/containerd/pull/3208
- [x] Address synchronous VM creation - https://github.com/firecracker-microvm/firecracker-containerd/pull/167
- [x] Add fake devices reservation (copy-paste from Runtime): #154
- [x] VM configuration defaults.
- [x] ~Implement persistency. containerd is designed to be able to stop and restart without the containers under management being interrupted. We  want to persist state outside of memory so we can recover~
- [x] Throw away obsolete code from Runtime (https://github.com/firecracker-microvm/firecracker-containerd/pull/182)
- [x] Switch to TTRPC (https://github.com/firecracker-microvm/firecracker-containerd/issues/180, https://github.com/firecracker-microvm/firecracker-containerd/pull/196)
- [x] Update example to use GRPC plugin (https://github.com/firecracker-microvm/firecracker-containerd/pull/182)
