### ISSUE TITLE
Remote snapshotter documentation

### ISSUE THREAD

**Issue by Kern--** [firecracker-microvm/firecracker-containerd#618]
We have all of the components to run remote snapshotters inside firecracker VMs, but the components are not documented. This issue tracks the needed documentation.

- [x] Remote snapshotter getting started guide (#686)
- [x] Remote snapshotter architecture doc (#695)
- [x]  demux-snapshotter documentation (#692)
- [x] http-address-resolver documentation (#692)
- [x] docker-credential-mmds documentation (#650)
